---
- name: Example playbook
  hosts: 169.47.251.23
  tasks:
    - name: testing 
      shell:
        cmd: ls -l | grep log
        chdir: /var/
    - name: test use of variables
      shell:
        cmd: rm ansible.txt
        cmd: "echo {{ var1 }} >> ansible.txt"
        chdir: /tmp
